// End-to-end smoke test: drives the MCP server over stdio exactly like a client,
// builds a demo deck exercising every scene type, then verifies the compiled app.
import { spawn } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const server = spawn(process.execPath, [path.join(ROOT, 'src/server.mjs')], { stdio: ['pipe', 'pipe', 'inherit'] });

let nextId = 1;
const pending = new Map();
let buf = '';
server.stdout.on('data', d => {
  buf += d;
  let nl;
  while ((nl = buf.indexOf('\n')) >= 0) {
    const lineText = buf.slice(0, nl); buf = buf.slice(nl + 1);
    if (!lineText.trim()) continue;
    const msg = JSON.parse(lineText);
    if (pending.has(msg.id)) { pending.get(msg.id)(msg); pending.delete(msg.id); }
  }
});
const rpc = (method, params) => new Promise((resolve, reject) => {
  const id = nextId++;
  pending.set(id, msg => msg.error ? reject(new Error(msg.error.message)) : resolve(msg.result));
  server.stdin.write(JSON.stringify({ jsonrpc: '2.0', id, method, params }) + '\n');
});
const call = async (name, args) => {
  const r = await rpc('tools/call', { name, arguments: args });
  if (r.isError) throw new Error(`${name}: ${r.content[0].text}`);
  return JSON.parse(r.content[0].text);
};
const assert = (cond, msg) => { if (!cond) throw new Error('ASSERT: ' + msg); };

const DECK = 'demo-flagship';

try {
  const init = await rpc('initialize', { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 'smoke', version: '0' } });
  assert(init.serverInfo.name === 'distributed-slides', 'serverInfo');
  const { tools } = await rpc('tools/list');
  assert(tools.length >= 15, 'tool count, got ' + tools.length);

  // Clean slate.
  try { await call('delete_deck', { deck: DECK }); } catch {}

  await call('create_deck', {
    id: DECK,
    title: 'Distributed-Slides / A demonstration performance',
    brand: 'DISTRIBUTED SYSTEMS',
    brandTag: 'DISTRIBUTED-SLIDES DEMO',
    badge: 'ENGINE DEMO / EVERY SCENE TYPE',
    footer: 'Demonstration deck generated by the Distributed-Slides smoke test. Synthetic data.',
  });

  const ref = await call('scene_reference', {});
  assert(Object.keys(ref.types).length === 30, 'scene types documented, got ' + Object.keys(ref.types).length);

  await call('add_scene', { deck: DECK, scene: {
    id: 'open', type: 'hero',
    title: 'Slides that behave like instruments, not documents',
    eyebrow: 'DISTRIBUTED SYSTEMS / DISTRIBUTED-SLIDES',
    subtitle: 'Every animation is a pure function of the clock.\nScrub it, replay it, mirror it to the audience window.',
    credit: 'Demonstration deck / synthetic data',
    chapter: 'The claim', duration: 20,
    notes: 'Open confidently. The point of this deck is that the animations are deterministic.',
    cue: 'Good evening.',
  }});

  await call('add_scene', { deck: DECK, scene: {
    id: 'thesis', type: 'statement',
    eyebrow: 'THE CONTRACT',
    title: 'mount(stage, scene) returns update(t) — and everything else follows',
    body: 'Because motion derives from the presenter clock, pausing, scrubbing, playback speed and the synchronized audience window are exact, not approximate.',
    chapter: 'The claim', duration: 14,
    notes: 'This is the single engineering decision the rest of the system falls out of.',
    cue: 'The whole system rests on one contract.',
  }});

  await call('add_scene', { deck: DECK, scene: {
    id: 'native', type: 'elements',
    title: 'Choreographed elements', chapter: 'The engines', duration: 18,
    background: '#F5F4EF',
    notes: 'Boxes, text, connectors — each enters on its own schedule.',
    cue: 'Here is the element engine.',
    elements: [
      { id: '1', x: 64, y: 54, w: 600, h: 28, text: [{ text: 'THE ELEMENT ENGINE', size: 14, color: '#215BEB', bold: true, align: 'l' }] },
      { id: '2', name: 'title-1', x: 64, y: 110, w: 1120, h: 150, text: [{ text: 'Any layout, any timing, one clock', size: 44, color: '#0C1524', bold: true, align: 'l', lineHeight: 1.05 }] },
      { id: 'a', x: 90, y: 330, w: 300, h: 130, geometry: 'roundRect', fill: '#FFFFFF', stroke: '#B8C7D8', strokeWidth: 1.5, anchor: 'ctr', insets: [14, 18, 14, 18], text: [{ text: 'Observation', size: 26, color: '#0C1524', bold: true, align: 'ctr' }] },
      { id: 'b', x: 500, y: 330, w: 300, h: 130, geometry: 'roundRect', fill: '#FFFFFF', stroke: '#B8C7D8', strokeWidth: 1.5, anchor: 'ctr', insets: [14, 18, 14, 18], text: [{ text: 'Decision', size: 26, color: '#0C1524', bold: true, align: 'ctr' }] },
      { id: 'c', x: 910, y: 330, w: 300, h: 130, geometry: 'roundRect', fill: '#0C1524', stroke: '#0C1524', strokeWidth: 0, anchor: 'ctr', insets: [14, 18, 14, 18], text: [{ text: 'Record', size: 26, color: '#FFFFFF', bold: true, align: 'ctr' }] },
      { kind: 'connector', from: 'a', to: 'b', x: 0, y: 0, w: 0, h: 0, stroke: '#215BEB', strokeWidth: 3, head: 'triangle' },
      { kind: 'connector', from: 'b', to: 'c', x: 0, y: 0, w: 0, h: 0, stroke: '#215BEB', strokeWidth: 3, head: 'triangle' },
      { x: 90, y: 560, w: 1100, h: 60, text: [{ text: 'Connectors draw themselves between elements; arrowheads and timing are automatic.', size: 24, color: '#3D4C5E', align: 'l' }] },
    ],
  }});

  await call('add_scene', { deck: DECK, scene: {
    id: 'system', type: 'diagram',
    title: 'The diagram engine assembles a system in narrated stages',
    subtitle: 'Nodes carry tone-coded spines; edges auto-route, draw on, and carry traveling dots.',
    chapter: 'The engines', duration: 36,
    notes: 'Watch the stages land in the order you would narrate them.',
    cue: 'Now the system diagram engine.',
    footnote: 'Synthetic demonstration topology.',
    phases: [
      { title: 'Sources produce evidence', body: 'Collectors preserve records with source and time.' },
      { title: 'Workers derive state', body: 'Derived records are readable by any process.' },
      { title: 'Serving and evaluation reuse the records', body: 'The same identifiers travel end to end.' },
    ],
    nodes: [
      { id: 'src', x: 65, y: 270, w: 280, h: 150, title: 'Sources', body: 'Feeds and venues', tone: 'blue', stage: 0 },
      { id: 'collect', x: 430, y: 270, w: 300, h: 150, title: 'Collectors', body: 'Continuous ingestion', tone: 'blue', stage: 0 },
      { id: 'db', x: 820, y: 255, w: 320, h: 185, title: 'Shared store', body: 'Evidence and derived records', tone: 'gold', stage: 1 },
      { id: 'work', x: 430, y: 520, w: 300, h: 150, title: 'Workers', body: 'Forecast and decide', tone: 'green', stage: 1 },
      { id: 'api', x: 1230, y: 270, w: 300, h: 150, title: 'Serving API', body: 'People, programs, models', tone: 'blue', stage: 2 },
      { id: 'grade', x: 1230, y: 520, w: 300, h: 150, title: 'Evaluation', body: 'Grades against outcomes', tone: 'amber', stage: 2 },
    ],
    edges: [
      { from: 'src', to: 'collect', stage: 0 }, { from: 'collect', to: 'db', stage: 0 },
      { from: 'db', to: 'work', stage: 1 }, { from: 'work', to: 'db', stage: 1 },
      { from: 'db', to: 'api', stage: 2 }, { from: 'db', to: 'grade', stage: 2, tone: 'amber' },
    ],
  }});

  const chartScenes = [
    { id: 'chart-bars', layout: 'bars', title: 'Bars grow and count in step with the clock',
      bars: [
        { label: 'Scene engines', value: 8, display: '8 engines', tone: 'blue' },
        { label: 'Chart layouts', value: 5, display: '5 layouts', tone: 'gold' },
        { label: 'Runtime dependencies', value: 0.4, display: '0 deps', tone: 'green', note: 'Fully offline output' },
      ], max: 8 },
    { id: 'chart-series', layout: 'series', title: 'Series reveal progressively with a live readout',
      series: { x: { min: 0, max: 24, label: 'Hour of day', ticks: 6 }, y: { min: 40, max: 90, format: '{v}°' },
        lines: [
          { label: 'Observed', tone: 'blue', points: Array.from({ length: 49 }, (_, i) => [i / 2, 62 + 14 * Math.sin((i / 2 - 6) / 24 * Math.PI * 2) + (i % 5) * .6]) },
          { label: 'Forecast', tone: 'gold', points: Array.from({ length: 49 }, (_, i) => [i / 2, 63 + 13 * Math.sin((i / 2 - 6.5) / 24 * Math.PI * 2)]) },
        ] } },
    { id: 'chart-timeline', layout: 'timeline', title: 'Timelines carry a traveling cursor',
      items: [
        { title: 'ORDER ACK', body: 'Resting at venue' },
        { title: 'CANCEL SENT', body: 'Awaiting response' },
        { title: 'FILL ARRIVES', body: 'Resolve executed quantity', tone: 'red' },
        { title: 'RECONCILE', body: 'Confirm remaining exposure' },
      ],
      band: { from: 1, to: 2, text: 'Exposure unresolved here.', tone: 'red' } },
    { id: 'chart-columns', layout: 'columns', title: 'Column panels land in narrated order',
      columns: [
        { title: 'Operate', tone: 'blue', boxes: [{ title: 'Presenter view', body: 'Notes, cues, clocks' }, { title: 'Audience window', body: 'Synchronized, note-free' }] },
        { title: 'Inspect', tone: 'gold', boxes: [{ title: 'Scene index', body: 'Search every scene' }, { title: 'Scrubber', body: 'Any moment, any speed' }] },
        { title: 'Extend', tone: 'green', boxes: [{ title: 'Custom scenes', body: 'SVG or canvas code' }, { title: 'Data channel', body: 'Real datasets, not props' }] },
      ] },
    { id: 'chart-table', layout: 'table', title: 'Tables fade in by row batch',
      headers: ['Engine', 'Kind', 'Chrome', 'Escape hatch'],
      rows: [
        ['hero', 'DOM', 'no', 'art + copy choreography'],
        ['elements', 'DOM', 'no', 'per-element enter overrides'],
        ['diagram', 'SVG', 'yes', 'explicit edge points'],
        ['chart', 'SVG', 'yes', 'five layouts'],
        ['custom', 'SVG or canvas', 'optional', 'arbitrary code'],
      ], monoColumns: [1] },
  ];
  for (const c of chartScenes) {
    await call('add_scene', { deck: DECK, scene: { type: 'chart', chapter: 'The engines', duration: 15, cue: 'Next: ' + c.layout + '.', notes: 'Chart layout ' + c.layout + '.', ...c } });
  }

  await call('set_data', { deck: DECK, key: 'lanes', value: {
    city: 'Boston', labels: ['58-59°', '60-61°', '62-63°', '64-65°', '66-67°', '68°+'],
    format: '{v}¢', highlightTitle: 'HIGHEST MIDPOINT',
    notes: ['Each lane keeps its own series identity.', 'Values are not normalized against each other.'],
    states: Array.from({ length: 145 }, (_, q) => ({
      minute: q * 10,
      values: Array.from({ length: 6 }, (_, b) => {
        const peak = 2.6 + 2.2 * Math.sin(q / 145 * Math.PI);
        const v = Math.exp(-Math.pow(b - peak, 2) / 1.4);
        return q % 29 === 7 && b === 5 ? null : Math.round(v * 88) / 100;
      }),
    })),
  }});

  await call('add_scene', { deck: DECK, scene: {
    id: 'native-lanes', type: 'lanes', dataRef: 'lanes',
    title: 'The lanes engine: six series in perspective, as a first-class type', chapter: 'The data engines', duration: 24,
    notes: 'The HEAT price topography, extracted: this is data plus one scene spec, no code.',
    cue: 'The topography is now a built-in.',
    footnote: 'Synthetic replay. Gaps in the source remain gaps on screen.',
  }});
  await call('add_scene', { deck: DECK, scene: {
    id: 'native-trajectory', type: 'trajectory', duration: 20,
    title: 'The trajectory engine: temperature × price × time', chapter: 'The data engines',
    notes: 'One minute is one point. The gold trail is the last 90 minutes.',
    cue: 'Same clock, different geometry.',
    trajectory: {
      x: { format: '{v}°F' }, y: { min: 0, max: 100, step: 20, format: '{v}¢' },
      panelTitle: 'LATEST MATCHED POINT',
      notes: ['The same x value can appear at different y values.', 'Retrospective example. No profit claim.'],
      points: Array.from({ length: 288 }, (_, i) => {
        const minute = i * 5, temp = 62 + 14 * Math.sin((minute / 60 - 6) / 24 * Math.PI * 2);
        return { minute, x: Math.round(temp * 10) / 10, y: Math.round(Math.exp(-Math.pow(temp - 68, 2) / 30) * 80 + i % 7) };
      }).filter((_, i) => i % 13 !== 5),
    },
  }});
  await call('add_scene', { deck: DECK, scene: {
    id: 'native-matrix', type: 'matrix', duration: 22, selectRotate: true,
    title: 'The matrix engine: ten panels, one shared clock, local offsets', chapter: 'The data engines',
    notes: 'Each panel keeps its own clock offset and bar geometry.',
    cue: 'Now scale it across panels.',
    matrix: {
      clock: { start: 480, span: 900, unit: 'UTC / SHARED CLOCK' }, format: '{v}¢',
      panels: Array.from({ length: 10 }, (_, p) => ({
        label: ['Boston', 'New York', 'Chicago', 'Denver', 'Seattle', 'Austin', 'Miami', 'Phoenix', 'Atlanta', 'Portland'][p],
        offset: [5, 5, 6, 7, 8, 6, 5, 7, 5, 8][p],
        barLabels: ['58', '60', '62', '64', '66', '68'],
        states: Array.from({ length: 97 }, (_, q) => ({
          minute: q * 15,
          values: Array.from({ length: 6 }, (_, b) => Math.round(Math.exp(-Math.pow(b - (1.5 + p % 4 + q / 97 * 2), 2) / 1.6) * 90) / 100),
        })),
      })),
    },
  }});
  await call('add_scene', { deck: DECK, scene: {
    id: 'native-cycle', type: 'cycle', duration: 26,
    title: 'The cycle engine: a workflow loop with retained artifacts', chapter: 'The data engines',
    notes: 'The active stage advances with the clock; the rail shows what must persist.',
    cue: 'And the conceptual loop.',
    clockUnit: 'WORKFLOW / NOT TELEMETRY',
    centerLabel: 'Responsibility survives the handoff',
    panelFooter: 'The model can change. This record persists.',
    steps: [
      { title: 'Observation', artifact: 'Timestamped evidence', detail: 'Preserve the source, path and observation time.' },
      { title: 'Belief', artifact: 'Versioned forecast', detail: 'Keep the model version and its evidence.' },
      { title: 'Pricing', artifact: 'Contract proposal', detail: 'Map belief to the venue geometry.' },
      { title: 'Risk gate', artifact: 'Recorded permission', detail: 'Check the mandate and limits.' },
      { title: 'Act or wait', artifact: 'Action receipt', detail: 'Record the order or the decision to wait.' },
      { title: 'Settlement', artifact: 'External outcome', detail: 'Attach the official result.' },
      { title: 'Evaluation', artifact: 'Accepted comparison', detail: 'Grade forecast and execution separately.' },
      { title: 'Policy review', artifact: 'Reviewed change', detail: 'Retain the experiment and authority.' },
    ],
  }});
  await call('add_scene', { deck: DECK, scene: {
    id: 'chart-cadence', type: 'chart', layout: 'cadence', duration: 16,
    title: 'Cadence: schedule rows with a sweeping cursor', chapter: 'The data engines',
    notes: 'Declared schedule marks; each row keeps its own offset.',
    cue: 'Even the ops story animates.',
    headline: '6 schedules', headlineSub: 'Each row keeps its actual interval and offset',
    caption: 'Declared schedule marks over one hour.',
    rows: [
      { label: 'weather-feed', intervalSec: 60 }, { label: 'orderbook-stream', intervalSec: 30 },
      { label: 'forecast-worker', intervalSec: 600, offsetSec: 120 }, { label: 'grading', intervalSec: 900 },
      { label: 'atlas-backtest', intervalSec: 1800, offsetSec: 300 }, { label: 'db-vacuum', intervalSec: 3600 },
    ],
  }});

  await call('add_scene', { deck: DECK, scene: {
    id: 'custom-lanes', type: 'custom', mode: 'canvas',
    title: 'Custom canvas: six quote lanes in perspective', chapter: 'The escape hatch', duration: 24,
    notes: 'This scene is user code — the same class of scene as the HEAT price topography.',
    cue: 'And when the built-ins are not enough, you write the scene.',
    code: `
const m = data.lanes, T = h.clamp(t / (scene.duration - 4)) * 1440;
h.txt(65, 48, 'DISTRIBUTED SLIDES / CUSTOM CANVAS SCENE', 16, C.muted, C.fontBody, 600);
h.wrapped(65, 141, scene.title, 1220, 43);
h.txt(65, 215, m.city + ' / six synthetic quote lanes / 0-100c', 19, C.muted);
h.ln([65, 238], [1535, 238], C.line);
const P = (minute, price, b) => [110 + minute / 1440 * 880 + b * 43, 770 - b * 49 - price * 240];
for (let b = 5; b >= 0; b--) {
  for (const q of [0, .5, 1]) h.ln(P(0, q, b), P(1440, q, b), q === 0 ? '#496078' : '#203449');
  h.txt(P(1440, 0, b)[0] + 15, P(1440, 0, b)[1] + 6, m.labels[b], 18, C.muted);
  g.beginPath();
  let valid = false;
  for (const q of m.states) {
    if (q.minute > T) break;
    const v = q.values[b];
    if (v === null) { valid = false; continue; }
    const pp = P(q.minute, v, b);
    valid ? g.lineTo(...pp) : g.moveTo(...pp);
    valid = true;
  }
  g.strokeStyle = b === 3 ? C.gold : C.blue; g.lineWidth = b === 3 ? 3.2 : 2.1; g.stroke();
}
for (let hr = 0; hr <= 24; hr += 6) { const q = P(hr * 60, 0, 0); h.txt(q[0], q[1] + 30, String(hr).padStart(2, '0') + ':00', 15, C.muted, C.fontMono, 400, 'center'); }
h.ln([65, 843], [1535, 843], C.line);
h.txt(65, 874, 'Synthetic replay / gaps remain gaps / drawn entirely from t', 14, C.muted);
`,
  }});

  await call('add_scene', { deck: DECK, scene: {
    id: 'custom-svg', type: 'custom', mode: 'svg',
    title: 'Custom SVG: the primitive kit with chrome for free', chapter: 'The escape hatch', duration: 15,
    subtitle: 'box, flow, group, text, value — the same kit the built-in engines use.',
    notes: 'SVG custom scenes get the standard chrome and caption bar without writing them.',
    cue: 'The SVG variant hands you the whole kit.',
    footnote: 'Demonstration scene authored as a code string through the MCP.',
    phases: [
      { title: 'Build once with primitives', body: 'The scene constructs on mount.' },
      { title: 'Register clock callbacks', body: 'onUpdate((t) => ...) drives every moving part.' },
      { title: 'The final frame holds', body: 'Motion off or reduced-motion renders the end state.' },
    ],
    code: `
const { C, box, flow, small, value, onUpdate, clamp } = api;
box(65, 290, 430, 170, 'Author scenes', 'Tools write JSON.\\nCode only when needed.', 'blue');
box(585, 290, 430, 170, 'Compile', 'One offline folder.\\nNo build server.', 'gold', .3);
box(1105, 290, 430, 170, 'Perform', 'Presenter + audience,\\nperfectly in step.', 'green', .6);
flow([[495, 375], [585, 375]], 1);
flow([[1015, 375], [1105, 375]], 3, C.gold);
small('SCENE CLOCK', 65, 560);
const readout = value('0.0s', 65, 640, 400, C.gold);
const bar = api.rect(65, 680, 0, 10, C.gold, 'none');
onUpdate((t, on) => {
  const tt = on ? t : api.scene.duration;
  readout.textContent = tt.toFixed(1) + 's';
  bar.setAttribute('width', 1470 * clamp(tt / api.scene.duration));
});
`,
  }});

  await call('add_scene', { deck: DECK, scene: {
    id: 'close', type: 'statement',
    eyebrow: 'DISTRIBUTED-SLIDES',
    title: 'Decks are specs. Performances are compiled.',
    body: 'create_deck, add_scene, set_route, build_deck.\nThe output runs from a folder, forever, offline.',
    chapter: 'Close', duration: 12,
    notes: 'Land the close and take questions.',
    cue: 'So that is the system.',
  }});

  // Catalog: one scene per remaining type and chart layout.
  const CH = 'The full vocabulary';
  const catalog = [
    { id: 'cat-quote', type: 'quote', title: 'The best way to predict the weather is to price it.', attribution: 'A trading desk proverb', role: 'Retold at every research review' },
    { id: 'cat-bullets', type: 'bullets', kicker: 'What ships in the box', title: 'Everything a talk needs, one clock', items: [
      { text: 'Presenter desk with notes and cues', detail: 'The audience never sees them.' },
      { text: 'Deterministic scrubbing', detail: 'Every frame is a function of t.' },
      { text: 'One offline folder', detail: 'No build server, no CDN.' }] },
    { id: 'cat-stats', type: 'stats', title: 'The engine in numbers', tiles: [
      { label: 'Scene types', value: 30, tone: 'gold' }, { label: 'Chart layouts', value: 21, tone: 'blue' },
      { label: 'Dependencies', value: 0, tone: 'green', note: 'Node stdlib only' }, { label: 'Output', value: 1, suffix: ' folder', tone: 'amber' }] },
    { id: 'cat-wall', type: 'wall', title: 'Runs anywhere a browser runs', items: ['Kalshi', 'Polymarket', 'Synoptic', 'NWS', 'IEM', 'Neon', 'Temporal', 'Zitadel', 'Stripe', 'turbopuffer'] },
    { id: 'cat-people', type: 'people', title: 'The desk', people: [
      { name: 'Arthur Collé', role: 'Distributed Systems' }, { name: 'HEAT', role: 'Research system' },
      { name: 'dsco', role: 'Agent' }, { name: 'You', role: 'Presenter' }] },
    { id: 'cat-countdown', type: 'countdown', title: 'Break', label: 'BACK IN', duration: 15 },
    { id: 'cat-terminal', type: 'terminal', title: 'Terminal', host: 'distributed.systems', lines: [
      { cmd: 'claude mcp add distributed-slides -- node src/server.mjs', out: 'Added stdio MCP server distributed-slides' },
      { cmd: 'ls decks/demo-flagship/dist', out: 'index.html  content.js  engine.js  shell.js  shell.css  stage.css' }] },
    { id: 'cat-code', type: 'code', title: 'The whole contract', highlights: [3], code: 'function mount(stage, scene, deck) {\n  // build once, then answer the clock\n  return { update(t, motionEnabled) { /* pure function of t */ } };\n}' },
    { id: 'cat-sequence', type: 'sequence', title: 'The audience window is a mirror', chapter: CH,
      actors: [{ id: 'p', label: 'Presenter' }, { id: 'a', label: 'Audience window' }, { id: 's', label: 'Scene engine' }],
      messages: [
        { from: 'p', to: 'a', label: 'ds-state {position, playing, speed}', mono: true },
        { from: 'a', to: 's', label: 'update(t)' }, { from: 'a', to: 'p', label: 'ds-ready', reply: true },
        { from: 'p', to: 's', label: 'update(t) — same t, same frame' }] },
    { id: 'cat-venn', type: 'venn', title: 'Where this engine lives', chapter: CH,
      sets: [{ label: 'Documents', note: 'Static slides' }, { label: 'Instruments', note: 'Deterministic motion' }], overlapLabel: 'Distributed-Slides' },
    { id: 'cat-pyramid', type: 'pyramid', title: 'What a scene is made of', chapter: CH, levels: [
      { title: 'Narration', body: 'notes and cues' }, { title: 'Choreography', body: 'delays and modes' },
      { title: 'Data', body: 'set_data payloads' }, { title: 'The clock', body: 'update(t)' }] },
    { id: 'cat-tree', type: 'tree', title: 'The deck compiles down', chapter: CH, root: {
      label: 'deck.json', tone: 'gold', children: [
        { label: 'content.js', children: [{ label: 'scenes' }, { label: 'routes' }, { label: 'data' }] },
        { label: 'runtime', children: [{ label: 'engine.js' }, { label: 'shell.js' }] },
        { label: 'assets' }] } },
    { id: 'cat-network', type: 'network', title: 'One store, many consumers', chapter: CH,
      nodes: [{ id: 'db', label: 'Shared store', tone: 'gold' }, { id: 'c1', label: 'Collector' }, { id: 'c2', label: 'Streamer' },
        { id: 'w', label: 'Forecast' }, { id: 'api', label: 'API' }, { id: 'g', label: 'Grading' }, { id: 'r', label: 'Research' }],
      links: [{ from: 'c1', to: 'db' }, { from: 'c2', to: 'db' }, { from: 'db', to: 'w', tone: 'blue' }, { from: 'db', to: 'api' }, { from: 'db', to: 'g' }, { from: 'db', to: 'r' }, { from: 'w', to: 'db' }] },
    { id: 'cat-wordcloud', type: 'wordcloud', title: 'What the audience remembers', chapter: CH, words: [
      { text: 'deterministic', weight: 10, tone: 'gold' }, { text: 'clock', weight: 8 }, { text: 'offline', weight: 7 },
      { text: 'presenter', weight: 6 }, { text: 'scrub', weight: 5 }, { text: 'mirror', weight: 5 }, { text: 'scenes', weight: 4 },
      { text: 'routes', weight: 4 }, { text: 'notes', weight: 3 }, { text: 'engine', weight: 3 }, { text: 'folder', weight: 3 }, { text: 'gaps stay gaps', weight: 2 }] },
    { id: 'cat-globe', type: 'globe', title: 'Twenty cities, one settlement clock', chapter: CH, caption: 'Stylized dot landmask / rotation derives from the scene clock',
      markers: [{ lat: 42.4, lon: -71, label: 'BOS' }, { lat: 40.8, lon: -74, label: 'NYC' }, { lat: 25.8, lon: -80.3, label: 'MIA' },
        { lat: 41.8, lon: -87.8, label: 'ORD' }, { lat: 33.4, lon: -112, label: 'PHX' }, { lat: 47.4, lon: -122.3, label: 'SEA' }],
      arcs: [{ from: 0, to: 4 }, { from: 1, to: 5 }, { from: 2, to: 3 }] },
    { id: 'cat-dotmap', type: 'dotmap', title: 'Stations reporting', chapter: CH, caption: 'Stylized landmask / marker pulses keyed to the clock',
      markers: [{ lat: 42.4, lon: -71, label: 'KBOS', value: '61°F' }, { lat: 39.9, lon: -75.2, label: 'KPHL', value: '63°F' },
        { lat: 33.6, lon: -84.4, label: 'KATL', value: '71°F' }, { lat: 51.5, lon: 0, label: 'EGLC', value: '14°C' }, { lat: 35.7, lon: 139.8, label: 'RJTT', value: '22°C' }] },
    { id: 'cat-race', type: 'race', title: 'Scene engines shipped, by week', chapter: CH, format: '{v}', caption: 'Interpolated ranks / every frame from t', rounds: [
      { label: 'Sep 14', values: [{ name: 'HEAT deck', value: 4 }, { name: 'Films', value: 16 }, { name: 'Engines', value: 0 }] },
      { label: 'Sep 15', values: [{ name: 'HEAT deck', value: 52 }, { name: 'Films', value: 52 }, { name: 'Engines', value: 4 }] },
      { label: 'Sep 16', values: [{ name: 'HEAT deck', value: 76 }, { name: 'Films', value: 52 }, { name: 'Engines', value: 8 }] },
      { label: 'Sep 17', values: [{ name: 'HEAT deck', value: 76 }, { name: 'Films', value: 52 }, { name: 'Engines', value: 30 }] }] },
    { id: 'cat-gallery', type: 'gallery', title: 'Gallery', images: [
      { src: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 40 22%22%3E%3Crect width=%2240%22 height=%2222%22 fill=%22%23132435%22/%3E%3C/svg%3E', caption: 'Panel A' },
      { src: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 40 22%22%3E%3Crect width=%2240%22 height=%2222%22 fill=%22%231b2f44%22/%3E%3C/svg%3E', caption: 'Panel B' },
      { src: 'data:image/svg+xml,%3Csvg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 40 22%22%3E%3Crect width=%2240%22 height=%2222%22 fill=%22%23234058%22/%3E%3C/svg%3E', caption: 'Panel C' }] },
    // chart layouts
    { id: 'cat-donut', type: 'chart', layout: 'donut', title: 'Share of scenes by engine class', chapter: CH, centerLabel: 'scenes', segments: [
      { label: 'Canvas data engines', value: 9, tone: 'gold' }, { label: 'SVG chrome engines', value: 12, tone: 'blue' }, { label: 'DOM typography', value: 9, tone: 'green' }] },
    { id: 'cat-gauge', type: 'chart', layout: 'gauge', title: 'Rehearsal pace', chapter: CH, value: 76, max: 100, label: 'Scenes rehearsed', format: '{v}%' },
    { id: 'cat-scatter', type: 'chart', layout: 'scatter', title: 'Effort against payoff', chapter: CH,
      x: { min: 0, max: 10 }, y: { min: 0, max: 10 }, quadrants: { labels: ['High payoff / low effort', 'High payoff / high effort', 'Low / low', 'Low payoff / high effort'] },
      points: [{ x: 2, y: 8.4, label: 'Reuse the clock', tone: 'gold', r: 11 }, { x: 7, y: 8.8, label: 'Custom scenes' }, { x: 3, y: 3, label: 'One-off tweaks' }, { x: 8, y: 2.5, label: 'Hand-animating', tone: 'red' }] },
    { id: 'cat-heatmap', type: 'chart', layout: 'heatmap', title: 'Quote coverage by hour', chapter: CH, showValues: false,
      rows: ['KBOS', 'KNYC', 'KMIA', 'KDEN'], cols: ['00', '03', '06', '09', '12', '15', '18', '21'],
      values: Array.from({ length: 4 }, (_, r) => Array.from({ length: 8 }, (_, c2) => Math.round(Math.exp(-Math.pow(c2 - 4 - r * .4, 2) / 6) * 100) / 100)) },
    { id: 'cat-histogram', type: 'chart', layout: 'histogram', title: 'Settlement error distribution', chapter: CH, overlay: true,
      bins: Array.from({ length: 17 }, (_, i) => ({ label: i - 8, count: Math.round(Math.exp(-Math.pow(i - 8, 2) / 8) * 96) + (i % 3) })) },
    { id: 'cat-waterfall', type: 'chart', layout: 'waterfall', title: 'Where the edge goes', chapter: CH, totalLabel: 'Net', steps: [
      { label: 'Gross edge', delta: 100 }, { label: 'Spread cost', delta: -28 }, { label: 'Fees', delta: -14 }, { label: 'Adverse fills', delta: -22 }, { label: 'Rebates', delta: 6 }] },
    { id: 'cat-slope', type: 'chart', layout: 'slope', title: 'Before and after calibration', chapter: CH, left: 'Raw model', right: 'Calibrated', format: '{v}', lines: [
      { label: 'Brier', a: 24, b: 17, tone: 'gold' }, { label: 'CRPS', a: 31, b: 22, tone: 'blue' }, { label: 'Log loss', a: 42, b: 30, tone: 'green' }] },
    { id: 'cat-funnel', type: 'chart', layout: 'funnel', title: 'From signal to fill', chapter: CH, note: 'Conversion between stages', stages: [
      { label: 'Signals', value: 1200 }, { label: 'Pass pre-trade gate', value: 640 }, { label: 'Orders placed', value: 410 }, { label: 'Filled', value: 285 }] },
    { id: 'cat-radar', type: 'chart', layout: 'radar', title: 'Engine coverage by need', chapter: CH,
      axes: ['Narrative', 'Data', 'Diagrams', 'Geo', 'Media', 'Typography'],
      series: [{ label: 'Distributed-Slides', values: [.95, .95, .9, .75, .8, .95], tone: 'gold' }, { label: 'Static decks', values: [.6, .35, .5, .3, .55, .7], tone: 'blue' }] },
    { id: 'cat-area', type: 'chart', layout: 'area', title: 'Observations ingested', chapter: CH, stacked: true,
      series: { x: { min: 0, max: 24, ticks: 6 }, y: { min: 0, max: 120 }, lines: [
        { label: 'ASOS', tone: 'blue', points: Array.from({ length: 25 }, (_, i) => [i, 30 + 18 * Math.sin((i - 6) / 24 * Math.PI * 2) + i]) },
        { label: 'Synoptic', tone: 'gold', points: Array.from({ length: 25 }, (_, i) => [i, 16 + 9 * Math.sin((i - 8) / 24 * Math.PI * 2)]) }] } },
    { id: 'cat-candles', type: 'chart', layout: 'candles', title: 'A contract session', chapter: CH, format: '{v}¢',
      candles: Array.from({ length: 24 }, (_, i) => { const base2 = 40 + 18 * Math.sin(i / 8) + i; const o = base2 + (i % 5) - 2, c2 = base2 + ((i * 7) % 9) - 4; return { o, c: c2, h: Math.max(o, c2) + 3 + i % 4, l: Math.min(o, c2) - 2 - i % 3, label: i }; }) },
    { id: 'cat-gantt', type: 'chart', layout: 'gantt', title: 'The migration plan', chapter: CH, format: 'D{v}', tasks: [
      { label: 'Export secrets', start: 0, end: 1, tone: 'gold' }, { label: 'Provision VPS', start: 0, end: 2 }, { label: 'Auth cutover', start: 2, end: 4 },
      { label: 'Router + Stripe', start: 4, end: 6 }, { label: 'MCP suite', start: 4, end: 8 }, { label: 'HEAT workers', start: 6, end: 10, tone: 'green' }] },
    { id: 'cat-bullet', type: 'chart', layout: 'bullet', title: 'Quarter targets', chapter: CH, format: '{v}', rows: [
      { label: 'Decks compiled', value: 34, target: 30, max: 50 }, { label: 'Scenes authored', value: 620, target: 800, max: 1000 }, { label: 'Live performances', value: 3, target: 4, max: 8 }] },
    { id: 'cat-calendar', type: 'chart', layout: 'calendar', title: 'Rehearsal days', chapter: CH, format: '{v} min',
      days: Array.from({ length: 84 }, (_, i) => ({ label: 'Day ' + (i + 1), value: Math.max(0, Math.round(45 * Math.exp(-Math.pow((i % 21) - 15, 2) / 40) + (i * 13 % 7))) })) },
    { id: 'cat-bump', type: 'chart', layout: 'bump', title: 'Model leaderboard by week', chapter: CH,
      rounds: ['W1', 'W2', 'W3', 'W4', 'W5'], series: [
        { label: 'Ensemble', ranks: [3, 2, 1, 1, 1], tone: 'gold' }, { label: 'NBM', ranks: [1, 1, 2, 3, 3], tone: 'blue' },
        { label: 'Persistence', ranks: [2, 3, 3, 2, 2], tone: 'green' }, { label: 'Raw GFS', ranks: [4, 4, 4, 4, 4], tone: 'red' }] },
  ];
  for (const scene of catalog) {
    await call('add_scene', { deck: DECK, scene: { chapter: CH, notes: 'Catalog scene: ' + (scene.layout || scene.type) + '.', cue: 'Next: ' + (scene.layout || scene.type) + '.', ...scene } });
  }

  await call('set_route', { deck: DECK, name: 'short', label: 'Short cut', sceneIds: ['open', 'thesis', 'system', 'custom-lanes', 'close'] });

  const validation = await call('validate_deck', { deck: DECK });
  assert(validation.ok, 'validation failed: ' + JSON.stringify(validation.problems));

  const built = await call('build_deck', { deck: DECK });
  assert(fs.existsSync(built.entry), 'dist entry exists');
  for (const f of ['content.js', 'engine.js', 'shell.js', 'shell.css', 'remote.js']) {
    assert(fs.existsSync(path.join(built.dist, f)), 'dist has ' + f);
  }
  const content = fs.readFileSync(path.join(built.dist, 'content.js'), 'utf8');
  assert(content.includes('custom-lanes') && content.includes('window.DECK='), 'content.js embeds scenes');

  // Negative paths.
  let rejected = false;
  try { await call('add_scene', { deck: DECK, scene: { id: 'bad', type: 'nope', title: 'x' } }); } catch { rejected = true; }
  assert(rejected, 'invalid scene type rejected');
  rejected = false;
  try { await call('set_route', { deck: DECK, name: 'x', sceneIds: ['missing-scene'] }); } catch { rejected = true; }
  assert(rejected, 'route with unknown scene rejected');
  rejected = false;
  try { await call('add_scene', { deck: DECK, scene: { id: 'bad-code', type: 'custom', title: 'x', code: 'this is not js ((' } }); } catch { rejected = true; }
  assert(rejected, 'unparseable custom code rejected');

  const summary = await call('get_deck', { deck: DECK });
  console.log('SMOKE PASS');
  console.log(JSON.stringify({ scenes: summary.scenes.length, routes: summary.routes, dist: built.dist, kb: Math.round(built.bytes / 1024) }, null, 2));
  process.exit(0);
} catch (e) {
  console.error('SMOKE FAIL:', e.message);
  process.exit(1);
} finally {
  server.kill();
}
