#!/usr/bin/env node
// Renders every scene in a route to an animated GIF by scrubbing its own
// deterministic clock, then assembles a zero-JS static gallery (index.html) —
// a "copy of the deck" a human can flip through with no server and no engine.
// CLI: node src/export-gifs.mjs <deck-id> [--route=name] [--fps=8] [--width=480] [--seconds=9]
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { loadDeck } from './store.mjs';
import { buildDeck } from './build.mjs';
import { serveDir } from './serve.mjs';
import { loadPlaywright, launchChromium, encodeGif } from './gif-kit.mjs';

const esc = s => String(s ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

function galleryHtml(deck, manifest) {
  const cards = manifest.map(m => `
  <figure>
    <img src="${esc(m.file)}" alt="${esc(m.title)}" loading="lazy">
    <figcaption><span>${esc(m.chapter || m.type)}</span><strong>${esc(m.title)}</strong></figcaption>
  </figure>`).join('');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(deck.title)} — GIF copy</title>
<style>
:root{--bg:#0a1521;--fg:#f6f3eb;--muted:#a4b3c3;--gold:#d5ad66;--line:#2b3947}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--fg);font-family:-apple-system,'Segoe UI',sans-serif;padding:48px 32px 80px}
h1{font-size:28px;font-weight:600;margin:0 0 6px}
p.sub{color:var(--muted);margin:0 0 40px;font-size:14px;max-width:720px;line-height:1.5}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(360px,1fr));gap:26px}
figure{margin:0;border:1px solid var(--line);background:#0d1c2b}
figure img{width:100%;display:block}
figcaption{padding:12px 14px}
figcaption span{display:block;font-size:10px;letter-spacing:1.4px;color:var(--gold);text-transform:uppercase;margin-bottom:4px}
figcaption strong{font-size:14px;font-weight:500}
</style></head>
<body>
<h1>${esc(deck.title)}</h1>
<p class="sub">A static GIF copy of every scene — no server, no JS engine required. Generated by Distributed-Slides' export_gifs tool. For a print/PDF copy instead, see print.html one level up.</p>
<div class="grid">${cards}</div>
</body></html>`;
}

export async function exportGifs(deckId, opts = {}) {
  const deck = loadDeck(deckId);
  const built = buildDeck(deck);
  const routeName = (opts.route && deck.routes[opts.route]) ? opts.route
    : (deck.routes[deck.defaultRoute] ? deck.defaultRoute : Object.keys(deck.routes)[0]);
  const ids = (opts.scenes && opts.scenes.length) ? opts.scenes : (deck.routes[routeName] || deck.scenes.map(s => s.id));
  const sceneMap = new Map(deck.scenes.map(s => [s.id, s]));
  const missing = ids.filter(id => !sceneMap.has(id));
  if (missing.length) throw new Error('Unknown scene ids: ' + missing.join(', '));

  const fps = opts.fps || 8;
  const width = opts.width || 480;
  const maxSeconds = opts.maxSeconds || 9;
  const outDir = path.join(built.dist, 'gifs');
  fs.rmSync(outDir, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });

  const { chromium } = loadPlaywright();
  const { server, port } = await serveDir(built.dist, 0);
  const browser = await launchChromium(chromium);
  const warnings = [];
  const manifest = [];
  try {
    const page = await browser.newPage({ viewport: { width: 1000, height: 563 } });
    await page.goto(`http://127.0.0.1:${port}/?screen=1`, { waitUntil: 'networkidle' });
    for (const id of ids) {
      const scene = sceneMap.get(id);
      const seconds = Math.max(.5, Math.min(scene.duration, maxSeconds));
      const frameDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ds-export-'));
      try {
        await page.evaluate(sid => window.DS_TEST.goTo(sid), id);
        await page.waitForTimeout(300);
        const n = Math.max(1, Math.round(seconds * fps));
        for (let f = 0; f <= n; f++) {
          await page.evaluate(t => window.DS_TEST.seek(t), (f / n) * seconds);
          await page.waitForTimeout(20);
          await page.screenshot({ path: path.join(frameDir, `f${String(f).padStart(4, '0')}.png`) });
        }
        const file = path.join(outDir, id + '.gif');
        encodeGif(frameDir, file, { fps, width });
        manifest.push({ id, title: scene.title || id, chapter: scene.chapter || '', type: scene.type, file: id + '.gif', bytes: fs.statSync(file).size });
      } catch (e) {
        warnings.push(`${id}: ${e.message}`);
      } finally {
        fs.rmSync(frameDir, { recursive: true, force: true });
      }
    }
  } finally {
    await browser.close();
    server.close();
  }

  fs.writeFileSync(path.join(outDir, 'manifest.json'), JSON.stringify({ deck: deck.id, title: deck.title, route: routeName, generatedAt: new Date().toISOString(), scenes: manifest }, null, 2));
  fs.writeFileSync(path.join(outDir, 'index.html'), galleryHtml(deck, manifest));

  return {
    dir: outDir, indexFile: path.join(outDir, 'index.html'), count: manifest.length,
    totalBytes: manifest.reduce((total, m) => total + m.bytes, 0), warnings,
  };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const [deckId, ...rest] = process.argv.slice(2);
  if (!deckId) { console.error('Usage: node src/export-gifs.mjs <deck-id> [--route=name] [--fps=8] [--width=480] [--seconds=9]'); process.exit(1); }
  const opts = {};
  for (const arg of rest) {
    const m = arg.match(/^--(\w+)=(.+)$/);
    if (!m) continue;
    const [, k, v] = m;
    opts[k === 'seconds' ? 'maxSeconds' : k] = /^\d+$/.test(v) ? Number(v) : v;
  }
  exportGifs(deckId, opts).then(r => {
    console.log(`Exported ${r.count} GIFs to ${r.dir} (${(r.totalBytes / 1024 / 1024).toFixed(1)} MB)`);
    if (r.warnings.length) console.log('Warnings:\n' + r.warnings.join('\n'));
  }).catch(e => { console.error('Export failed:', e.message); process.exit(1); });
}
